AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation template for project COAST. Provisions AWS Managed Grafana workspace and associate with a workspace role.

###########################################################################
# Author: Chris Strzelczyk
# Project: COAST: https://github.com/aws-samples/coast-grafana-cost-intelligence-dashboards
###########################################################################

Parameters:
  ResourcePrefix:
    Type: String
    Default: "coast"
    Description: "Prefix used Amazon Managed Grafana workspace name and for the value of tag key 'project'"
    MaxLength: 16 
    AllowedPattern: "^[a-z0-9]+[a-z0-9-]{1,61}[a-z0-9]+$"

Resources:

###########################################################################
# Create Amazon Managed Grafana workspace and necessary role/permissions
###########################################################################
  
  GrafanaWorkspace: #Create Grafana workspace
    Type: AWS::Grafana::Workspace
    DependsOn: 
      - GrafanaWorkspaceRole
    Properties: 
      AccountAccessType: CURRENT_ACCOUNT
      AuthenticationProviders: 
        - AWS_SSO
      DataSources: 
        - CLOUDWATCH
        - ATHENA
      Description: 'COAST Project Workspace'
      GrafanaVersion: '10.4'
      PluginAdminEnabled: true
      Name:
        !Sub 
        - ${ResourcePrefix}-workspace-${UniqueString}
        - UniqueString: !Select [ 0, !Split [ '-', !Select [ 2, !Split [ '/', !Ref 'AWS::StackId' ] ] ] ]
      NotificationDestinations: 
        - SNS
      PermissionType: SERVICE_MANAGED
      RoleArn: !Ref GrafanaWorkspaceRole

  GrafanaWorkspaceRole: 
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: 'grafana.amazonaws.com'
          Action: 'sts:AssumeRole'
      Description: 'COAST Grafana Workspace Role'
      Tags:
        - Key: "project"
          Value: "coast"
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/service-role/AmazonGrafanaAthenaAccess'
        - 'arn:aws:iam::aws:policy/service-role/AmazonGrafanaCloudWatchAccess'
      Path: /
  
  SNSNotificationsTopic: #SNS Notification for Grafana
    Type: 'AWS::SNS::Topic'
    Properties:
      Tags:
        - Key: "project"
          Value: "coast"
      TopicName:
        !Sub 
        - ${ResourcePrefix}-notification-${UniqueString}
        - UniqueString: !Select [ 0, !Split [ '-', !Select [ 2, !Split [ '/', !Ref 'AWS::StackId' ] ] ] ]

Outputs:
  GrafanaWorkspaceID:
    Description: "Grafana Workspace ID"
    Value: !Ref GrafanaWorkspace

  GrafanaWorkspaceName:
    Description: "Grafana Workspace Name"
    Value: !GetAtt GrafanaWorkspace.Name
  
  GrafanaRoleArn:
    Description: "Grafana Role ARN"
    Value: !Ref GrafanaWorkspaceRole
  
  SNSNotificationsTopic:
    Description: "SNS Notification Topic for Grafana"
    Value: !Ref SNSNotificationsTopic