site_name: COAST - Cost Optimation and Savings Tool for Amazon Managed Grafana
docs_dir: "docs"
copyright: "Copyright © Amazon 2023"
site_author: "AWS"
site_url: "https://aws-samples.github.io/cost-dashboard-for-amazon-managed-grafana/"


theme:
  logo: images/aws-logo.png
  favicon: images/aws-favicon.png
  name: material
  font:
    text: ember
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime  





markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.critic
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "¤"
  - toc:
      permalink: true
plugins:
  - search


copyright: |
  &copy; 2023 <a href="https://aws-samples.github.io/cost-dashboard-for-amazon-managed-grafana/"  target="_blank" rel="noopener">COAST @ AWS</a>  